### ISSUE TITLE
ImportError: cannot import name '_to_hours_mins_secs'

### ISSUE THREAD

**Issue by Blossomone** [kedz/nnsum#16]
I run the program but got error: ImportError: cannot import name '_to_hours_mins_secs'
Can you guide me how to solve this error. 
Thanks.
```
(nnsum) C:\Users\17674\Desktop\MultiModalSummary\nnsum-master>python script_bin/train_model.py --trainer --train-inputs data\ami.v2\inputs\train --train-labels data\ami.v2\labels\train --valid-inputs data\ami.v2\inputs\valid --valid-labels data\ami.v2\labels\valid --valid-refs data\ami.v2\human-abstracts\valid  --weighted --model save --results log --seed 12345678 --emb --pretrained-embeddings D:\Code\Glove\glove.42B.300d.txt  --enc cnn --ext s2s --bidirectional
Traceback (most recent call last):
  File "script_bin/train_model.py", line 4, in <module>
    import nnsum
  File "C:\Users\17674\anaconda3\envs\nnsum\lib\site-packages\nnsum-1.0-py3.6.egg\nnsum\__init__.py", line 4, in <module>
  File "C:\Users\17674\anaconda3\envs\nnsum\lib\site-packages\nnsum-1.0-py3.6.egg\nnsum\trainer\__init__.py", line 1, in <module>
  File "C:\Users\17674\anaconda3\envs\nnsum\lib\site-packages\nnsum-1.0-py3.6.egg\nnsum\trainer\labels_mle_trainer.py", line 8, in <module>
ImportError: cannot import name '_to_hours_mins_secs'
```

**Comment by YoussephAhmed** [comment]
+1 did you find a fix for it?
